name: paw
description: Small, organised and customizable logger for your flutter and dart apps.
version: 0.0.4
repository: https://github.com/AdityaMotale/paw

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  test: ^1.16.8
  lints: ^2.0.1

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
